### ISSUE TITLE
Use SQLAlchemy filter operators instead of magic__string__kwargs for filtering?

### ISSUE THREAD

**Issue by patrys** [encode/orm#14]
Django's approach leads to ugly code (`order_line__variant__product__name__icontains=...` etc.), does not allow for explicit aliasing and breaks things like static type checking and autocomplete (PyCharm has tons of Django-specific code to get basic autocomplete to work).

I think it should be possible to use the Alechemy's query builder given that it works in GINO:

https://docs.sqlalchemy.org/en/latest/orm/tutorial.html#common-filter-operators

**Comment by tomchristie** [comment]
We could defiantly consider that, yup.

**Comment by patrys** [comment]
Here's a project that also uses Databases internally but relies on the existing filter syntax: https://github.com/vinissimus/asyncom

**Comment by aminalaee** [comment]
This is pretty old, but a good idea indeed.
