### ISSUE TITLE
ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by lexdene** [encode/orm#19]
I installed orm in a clean virtualenv, and import orm.fields, it raised a ModuleNotFoundError error.

    ->  python3 -m venv venv
    ->  source venv/bin/activate
    ->  pip install orm
    Collecting orm
      Using cached https://files.pythonhosted.org/packages/c6/a6/4a867c58f4bcab01cf782f91a58f37b4a93f390aba89a7f1c3410f9454fe/orm-0.1.2.tar.gz
    Collecting databases (from orm)
      Using cached https://files.pythonhosted.org/packages/f5/0b/e4959843279b6e8ebe638f9f52f4fb403c33ae621f3fbd5b6a8c973c7752/databases-0.2.1.tar.gz
    Collecting typesystem (from orm)
      Using cached https://files.pythonhosted.org/packages/ee/a3/2220dc25ddc8461ac405fe3f2f02cc2dd7360c9be597128aa905eda1c5b7/typesystem-0.2.0.tar.gz
    Collecting sqlalchemy (from databases->orm)
      Using cached https://files.pythonhosted.org/packages/85/29/d7a5687d0d21ea8133f2d4ef02dfb4d191afe7ebc8bd9f962d99bdf595e1/SQLAlchemy-1.3.1.tar.gz
    Installing collected packages: sqlalchemy, databases, typesystem, orm
      Running setup.py install for sqlalchemy ... done
      Running setup.py install for databases ... done
      Running setup.py install for typesystem ... done
      Running setup.py install for orm ... done
    Successfully installed databases-0.2.1 orm-0.1.2 sqlalchemy-1.3.1 typesystem-0.2.0
    You are using pip version 18.1, however version 19.0.3 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    ->  python
    Python 3.7.2 (default, Dec 27 2018, 07:35:06)
    [Clang 10.0.0 (clang-1000.11.45.5)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from orm import fields
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "~/test-orm/venv/lib/python3.7/site-packages/orm/__init__.py", line 2, in <module>
        from orm.fields import Boolean, Integer, Float, String, Text, Date, Time, DateTime, JSON, ForeignKey
      File "~/test-orm/venv/lib/python3.7/site-packages/orm/fields.py", line 5, in <module>
        from attr import attrs
    ModuleNotFoundError: No module named 'attr'
    >>>

**Comment by tomchristie** [comment]
Thanks! Got resolved in https://github.com/encode/orm/commit/3f0b9d5f665a54a6d2ddbf921c810c4674d7d710 but didn't push a release to PyPI.
I've just done that now - upgrade to 0.1.3 and you'll be good to go.
