### ISSUE TITLE
Feature Request: save() method for models

### ISSUE THREAD

**Issue by HarrySky** [encode/orm#20]
**Problem**: If I create new model and want to save it - I need to use `await ModelClass.objects.create(column_name=model.column_name, ...)`.

**Solution**: Just call something like `model.save()` the same way `model.update()` is used right now. Also `model.save()` can fallback to `model.update()` if id is set.

Maybe I am missing something and there is another easy and clean way to add a new row, I am ready to use it or implement one.

**Comment by HarrySky** [comment]
Did not test if something like this will work:

```
class SaveableModel(Model):
    def save(self):
        self.objects.create(**self.fields.items())
```

**Comment by HarrySky** [comment]
It does not work, gives `typesystem.base.ValidationError: {'id': 'Must be a number.', ...`

**Comment by tomchristie** [comment]
Instead of...

```python
model = ModelClass()
model.string_field = 'Test' # db.StringField()
model.int_field = 5 # db.IntField()
model.bool_field = False # db.BooleanField()
await model.save()
```

Use this...

```
instance = await ModelClass.objects.create(
    string_field=...,
    int_field=...,
    bool_field=...
)
```

If you really need to build it up gradually you can use this pattern...

```
kwargs = {}
kwargs['string_field'] = 'Test'
kwargs['int_field'] = 5
kwargs['bool_field'] = False
instance = await ModelClass.objects.create(**kwargs)
```

Having partially populated model instances, or modifiying model instance properties directly is a problematic pattern and means that model instances don't do a good job of encapsulating valid state changes.

**Comment by tomchristie** [comment]
Related: https://www.dabapps.com/blog/django-models-and-encapsulation/

**Comment by HarrySky** [comment]
Thanks, did not know that this is problematic pattern :)
