### ISSUE TITLE
What is the reason for handcrafting QuerySet class from scratch?

### ISSUE THREAD

**Issue by kiddick** [encode/orm#29]
There is already Query class here https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/query.py with all powerful staff included. I mean it could be based on that

**Comment by tomchristie** [comment]
There's 5000 lines of code that's not trivial to pick apart.

I'd *totally* love for someone with more experience of working in depth with SQLAlchemy to take a crack at an SQLAlchemy-style integration on top of databases, but that's not the approach I'm planning to take here.
