### ISSUE TITLE
Any plans to add classic approach with sessions to manage transactions state durign HTTP requests?

### ISSUE THREAD

**Issue by kiddick** [encode/orm#31]
Especially useful for integrations with REST API frameworks. Let's discuss.

**Comment by tomchristie** [comment]
I take it you mean holding on to changes in state, and flushing the session in one go.

No plans for that, nope.

The general pattern you end up with is "let's just wrap the entire endpoint up in a transaction, always" - that's a very blunt approach. Suppose we have an endpoint that issues an HTTP request as part of it's operation - we *really* don't want to be holding onto a database connection or transaction for the duration of the request. We need instead to be making sure that there's:

* Automatically handled fine-grained transactionality for stuff like uniqueness constraints.
* Explicitness about coarser-grained transactions if you're wrapping up multiple operations across different tables.

Having said that, I'm very much in favor of contributors tackling other ORM styles on top of databases.
