### ISSUE TITLE
Support UUID

### ISSUE THREAD

**Issue by zezic** [encode/orm#39]
Do you plan to support UUID type and allow it to be used as a primary key?

**Comment by thiagovarela** [comment]
Hey, have you tried something like: 
```python
# fields.py
from sqlalchemy.dialects.postgresql import UUID
class UUIDField(ModelField, typesystem.String):
    def get_column_type(self):
        return UUID()

# models.py
class Thingy(orm.Model):
    id = UUIDField(default=uuid4, format="uuid", primary_key=True)
```

**Comment by unitto1** [comment]
@thiagovarela seems it's not enough
when we use `as_uuid=False` we expect to get an `str` object from DB
when we use `as_uuid=True` we expect to get `uuid.UUID` object from DB

but actually we get `asyncpg.pgproto.pgproto.UUID` in any case.

Can we implement something like a `to_python` method?
