### ISSUE TITLE
Pydentic support, server_default

### ISSUE THREAD

**Issue by unitto1** [encode/orm#50]
Hey! Have you any plans for using pydantic instead of typesystem or add support of it?

Also, it will be great to have opportunity to use the UUID field and server_default.

**Comment by tomchristie** [comment]
> Have you any plans for using pydantic instead of typesystem or add support of it?

The internal library used for validation shouldn't really be relevant to the user - though we *do* need to make sure that we adequately support whatever custom user validation you want to use. 

So, no we won't have pydantic support *built-in*, but yes, we will want to support arbitrary user-defined model validations. (Which could perfectly well include pydantic)

> Also, it will be great to have opportunity to use the UUID field and server_default.

Noted, yup.

Sidenote: I've personally not had a lot of time on orm lately, though I am getting around to it slowly.

**Comment by garyd203** [comment]
Hey @unitto1 we have some local extensions that include support for `server_default` and `server_onupdate`. There's no test coverage and I'm not confident I've done it correctly (although it Works For Me on postgres), but I can post a gist here if you are interested
