### ISSUE TITLE
Add '.exclude()' method

### ISSUE THREAD

**Issue by rick-pri** [encode/orm#51]
I want to select rows with a query where the values are not `None` when I've set a field as `allow_null=True`.  It's very possible that I'm missing something and that this can be achieved in another way.

**Comment by tomchristie** [comment]
Yup, we'd certainly want to add an `.exclude()` method. (Even if this particular request *can* be achieved in another way.)

**Comment by myuz** [comment]
@tomchristie @florimondmanca 

I would happy to work on the ticket, also one more question how you image the functionality? it would be helpful for me to understand the problem from all corners.

Because, in my head, I have something like

```
User.filter(...).exclude(address=None).all()
```

**Comment by rafalp** [comment]
@myuz Hi, there's already PR for this issue, with the only issue reported in review being syntax used: https://github.com/encode/orm/pull/62

If we'll agree that PR is good otherwise I'll be happy to change my review to approved. Or we could fork PR to fix syntax and merge fork instead.

**Comment by myuz** [comment]
Hi @rafalp thanks for sharing it, I'll follow-up PR.

**Comment by collerek** [comment]
Hi,

This project seems stale and from what I saw on encode page it's not a priority right now. Since I was tired with reinventing the wheel and needed something as soon as possible I created ormar package, that was inspired by this one. 

Ormar bases its validation on pydantic so it can be used directly with fastapi as response and request models.

This issue was implemented in ormar, so feel free to check it  out: https://github.com/collerek/ormar

**Comment by aminalaee** [comment]
Done in #62.

**Comment by pranto157** [comment]
```
In [24]: ob.dict()
Out[24]: 
{'account_link': None,
 'balance': None,
 'last_payout': {'created': datetime.datetime(1970, 5, 23, 21, 17, 35, tzinfo=datetime.timezone.utc),
  'amount': 10.0},
 'last_transactions': None,
 'stripe_account_data': None,
 'stripe_account_id': '1',
 'stripe_account_status': 'OK'}
```

So this is my pydentic `dict`, but when I'm going to apply exclude for some fields, getting type error. any idea? 
```
In [23]: ob.dict(exclude={'last_payout': {'created'}, 'balance':True})
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-79efff7cb2cb> in <module>
----> 1 ob.dict(exclude={'last_payout': {'created'}, 'balance':True})

~/.cache/pypoetry/virtualenvs/shorepay-8aoaCqjR-py3.8/lib/python3.8/site-packages/pydantic/main.cpython-38-x86_64-linux-gnu.so in pydantic.main.BaseModel.dict()

~/.cache/pypoetry/virtualenvs/shorepay-8aoaCqjR-py3.8/lib/python3.8/site-packages/pydantic/main.cpython-38-x86_64-linux-gnu.so in _iter()

~/.cache/pypoetry/virtualenvs/shorepay-8aoaCqjR-py3.8/lib/python3.8/site-packages/pydantic/main.cpython-38-x86_64-linux-gnu.so in pydantic.main.BaseModel._get_value()

~/.cache/pypoetry/virtualenvs/shorepay-8aoaCqjR-py3.8/lib/python3.8/site-packages/pydantic/utils.cpython-38-x86_64-linux-gnu.so in pydantic.utils.ValueItems.__init__()

TypeError: Unexpected type of exclude value <class 'bool'>
```
