### ISSUE TITLE
No active deveopment ? Is the project abandoned

### ISSUE THREAD

**Issue by aurthurm** [encode/orm#83]
It seems there is no active deveopmnt. Is the project still maintained?

**Comment by Atem18** [comment]
I would say that since sqlalchemy orm will get async support, that project will probably not be needed anymore. And probably encode/databases as well. 

https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html

**Comment by aurthurm** [comment]
Thanks @Atem18
