### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by logileifs** [encode/orm#89]
I'm following the documentation and trying to use async postgres connection, everything seems to work fine until this line:
`engine = sqlalchemy.create_engine(str(database.url))`

then I just get this error:
```
~/.virtualenvs/asyncsql/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py in create_engine(*args, **kwargs)
    518     strategy = kwargs.pop("strategy", default_strategy)
    519     strategy = strategies.strategies[strategy]
--> 520     return strategy.create(*args, **kwargs)
    521 
    522 

~/.virtualenvs/asyncsql/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py in create(self, name_or_url, **kwargs)
     85                 if k in kwargs:
     86                     dbapi_args[k] = pop_kwarg(k)
---> 87             dbapi = dialect_cls.dbapi(**dbapi_args)
     88 
     89         dialect_args["dbapi"] = dbapi

~/.virtualenvs/asyncsql/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py in dbapi(cls)
    776     @classmethod
    777     def dbapi(cls):
--> 778         import psycopg2
    779 
    780         return psycopg2

ModuleNotFoundError: No module named 'psycopg2'
```

If I install psycopg2 everything works fine but I thought it should work with only asyncpg
Is psycopg2 a requirement even for async postgres?

**Comment by miss85246** [comment]
Hello, I also encountered a similar problem. I found that the version on pipy is 0.1.5, but the version on github is 0.1.4. Please try to install 0.1.4, which may solve your problem.

**Comment by meysam81** [comment]
@miss85246 @logileifs 
Have you tried `pip install databases[postgresql]`?

**Comment by Euromance** [comment]
@meysam81 @logileifs 
`databases[postgresql]` would only install `asyncpg`, which is an asynchronous driver.
`SQLAlchemy` itself is a synchronous library and it requires a synchronous driver to work with the database. It does not install any by default as it works with multiple backends.`psycopg2` in the provided example is only required to create the database and run migrations, which you can do in any other ways available. It's not required by `encode/orm` itself.
