### ISSUE TITLE
Maintainer Needed

### ISSUE THREAD

**Issue by xloem** [encode/orm#96]
It looks like the project maintainers may have abandoned this project, given it has been a year since the last commit.

@tomchristie @florimondmanca @rzane @thiagovarela @dopry @kcrebound @Lynskylate
is this true, that the project is no longer maintained?

@aminalaee #95 @pykulytsky #92 @GDWR #91 @david-alm #86 @Blue-Hope #76 @AndTheDaysGoBy #73 @asnelling #71
Are any of you available to take on this project and maintain or fork it?

**Comment by tomchristie** [comment]
Hi @xloem - So we can easily add anyone onto the maintainers team, and help folks through what's required to release new versions to PyPI. If anyone wants to be added to @encode/maintainers, just ask.
